/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Root ping */
    get: operations['AppController_ping'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness health check */
    get: operations['AppController_health'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register new user */
    post: operations['AuthController_register'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login with username + password */
    post: operations['AuthController_login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Rotate refresh token + issue new access */
    post: operations['AuthController_refresh'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Revoke refresh + clear cookies */
    post: operations['AuthController_logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Current authenticated user */
    get: operations['AuthController_me'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/change-password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Change password (FR-11.3) — verify current + revoke other refresh tokens */
    post: operations['AuthController_changePassword'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/{id}/activity': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Activity timeline hybrid (FR-13) — self/admin only */
    get: operations['ActivityController_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/notifications': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List notifications của current user, filter all|unread, paginated */
    get: operations['NotificationsController_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/notifications/unread-count': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Số notification chưa đọc của current user */
    get: operations['NotificationsController_unreadCount'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/notifications/mark-all-read': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Đánh dấu tất cả notification của user là đã đọc */
    patch: operations['NotificationsController_markAllRead'];
    trace?: never;
  };
  '/notifications/{id}/read': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Đánh dấu 1 notification đã đọc/chưa đọc (self-scope) */
    patch: operations['NotificationsController_markRead'];
    trace?: never;
  };
  '/notifications/bulk-read': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Đánh dấu nhiều notification đã đọc (self-scope, ids khác user bị skip) */
    patch: operations['NotificationsController_bulkMarkRead'];
    trace?: never;
  };
  '/notifications/all': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Xóa tất cả notification của current user */
    delete: operations['NotificationsController_deleteAll'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/notifications/bulk': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Xóa nhiều notification (self-scope, ids không thuộc user bị skip) */
    delete: operations['NotificationsController_deleteBulk'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/notifications/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Xóa 1 notification (self-scope) */
    delete: operations['NotificationsController_deleteOne'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List users (admin only) */
    get: operations['UsersController_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/me/avatar/sign': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Issue Cloudinary signed params cho self avatar upload (FR-11.7) */
    post: operations['UsersController_signAvatar'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/me/avatar': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Remove avatar (FR-11.7) — Cloudinary destroy + null fields */
    delete: operations['UsersController_removeAvatar'];
    options?: never;
    head?: never;
    /** Save avatar sau khi FE upload Cloudinary success (FR-11.7) — cleanup avatar cũ */
    patch: operations['UsersController_setAvatar'];
    trace?: never;
  };
  '/users/by-username/{username}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Public lookup by username (FR-11.1) — email hidden */
    get: operations['UsersController_getByUsername'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/{id}/stats': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Profile stats: posts/likes/views + streak + heatmap28d (FR-11.4) */
    get: operations['UsersController_getStats'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get user by id (admin hoặc self) */
    get: operations['UsersController_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update user (admin hoặc self) — email/avatar/title/bio/skills */
    patch: operations['UsersController_update'];
    trace?: never;
  };
  '/users/{id}/ban': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Ban user (admin only) — set role BANNED + revoke refresh tokens */
    post: operations['UsersController_ban'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/{id}/unban': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Unban user (admin only) — set role USER */
    post: operations['UsersController_unban'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/files/sign': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Issue signed upload params (admin only) — cloudinary | local */
    post: operations['FilesController_signUpload'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/files/upload': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Upload file vào local volume (admin only, STORAGE_DRIVER=local) */
    post: operations['FilesController_upload'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/files/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete file (admin only) — DB record + revoke storage asset */
    delete: operations['FilesController_remove'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/tags': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List popular tags (public, top N by postCount DESC) */
    get: operations['TagsController_list'];
    put?: never;
    /** Create tag (admin only) — auto-assign color nếu thiếu */
    post: operations['TagsController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/tags/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete tag (admin only). ?force=true để xóa khi tag đang được dùng */
    delete: operations['TagsController_remove'];
    options?: never;
    head?: never;
    /** Update tag (admin only) */
    patch: operations['TagsController_update'];
    trace?: never;
  };
  '/posts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List posts (public, paginated, optional mood/tag filter) */
    get: operations['PostsController_list'];
    put?: never;
    /** Create post (admin only) */
    post: operations['PostsController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/posts/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get post by id (public) */
    get: operations['PostsController_get'];
    put?: never;
    post?: never;
    /** Delete post (admin only, hard delete with cascade) */
    delete: operations['PostsController_remove'];
    options?: never;
    head?: never;
    /** Update post (admin only, partial) */
    patch: operations['PostsController_update'];
    trace?: never;
  };
  '/posts/{id}/view': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Track view (public, optional auth, dedup 30min) */
    post: operations['PostsController_trackView'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/posts/{id}/reactions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List users đã react, optional filter by type, paginated */
    get: operations['ReactionsController_listReactions'];
    put?: never;
    /** Upsert reaction cho post (optional auth, idempotent) */
    post: operations['ReactionsController_upsertReaction'];
    /** Xóa reaction của actor khỏi post */
    delete: operations['ReactionsController_removeReaction'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/posts/{id}/reactions/counts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Aggregate reaction counts cho post (public, myReaction nếu có viewer) */
    get: operations['ReactionsController_getReactionCounts'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/posts/{id}/like': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** [DEPRECATED] Use POST /posts/:id/reactions instead */
    post: operations['ReactionsController_legacyLike'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/comments/{id}/like': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Toggle like cho comment APPROVED (binary, optional auth) */
    post: operations['ReactionsController_toggleCommentLike'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/interaction-logs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List interaction trace logs (admin, paginated + filter) */
    get: operations['InteractionLogsController_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/posts/{id}/comments': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List comments (public role-aware: USER chỉ APPROVED, admin tất cả status) */
    get: operations['CommentsController_list'];
    put?: never;
    /** Create comment (optional auth, default status APPROVED) */
    post: operations['CommentsController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/comments/{id}/replies': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List replies of a comment (FR-03.6, paginated, role-aware status filter) */
    get: operations['CommentsController_listReplies'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/comments/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete comment (admin only, cascade CommentLike) */
    delete: operations['CommentsController_remove'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/comments/{id}/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Moderate status (admin only) — APPROVED | REJECTED */
    patch: operations['CommentsController_updateStatus'];
    trace?: never;
  };
  '/posts/{id}/save': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Toggle bookmark (auth user only, idempotent) */
    post: operations['SavedController_toggle'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/me/saved': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List saved posts của current user (paginated, sort savedAt DESC) */
    get: operations['SavedController_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/search': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Full-text search Postgres ILIKE multi-table (FR-12.1) */
    get: operations['SearchController_query'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/test-reset': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reset DB + reseed test fixtures (E2E only, env-gated) */
    post: operations['AdminController_testReset'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/stats': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 4 metrics aggregation + 12-day sparkline + delta today */
    get: operations['AdminController_stats'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/moods': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Mood distribution zero-filled 7 moods */
    get: operations['AdminController_moods'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/comments': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Cross-post comment moderation queue (FR-07.4) */
    get: operations['AdminController_listComments'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/heatmap': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 28-day post creation heatmap */
    get: operations['AdminController_heatmap'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/posts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all posts (any status) with filters */
    get: operations['AdminController_listPosts'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/posts/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Hard-delete post + Cloudinary assets */
    delete: operations['AdminController_deletePost'];
    options?: never;
    head?: never;
    /** Update post content/mood/status/tags */
    patch: operations['AdminController_updatePost'];
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    RegisterDto: {
      /** @example kha */
      username: string;
      /** @example strong-password-123 */
      password: string;
      /** @example kha@example.com */
      email?: string;
    };
    AuthUserDto: {
      /** @example cmpa14i8t000010ldmv5j5att */
      id: string;
      /** @example kha */
      username: string;
      /** @example kha@example.com */
      email: Record<string, never> | null;
      /**
       * @example ADMIN
       * @enum {string}
       */
      role: 'ADMIN' | 'USER' | 'BANNED';
      /** @example https://...cloudinary.../avatar.jpg */
      avatarUrl: Record<string, never> | null;
      /** @example avatars/u-alice-1234 */
      avatarPublicId?: Record<string, never> | null;
      /** @example Full-stack Developer */
      title?: Record<string, never> | null;
      /** @example Bio markdown... */
      bio?: Record<string, never> | null;
      /**
       * @description Skills `[{ name, color }]`
       * @example [
       *       {
       *         "name": "TypeScript",
       *         "color": "#7DCFFF"
       *       }
       *     ]
       */
      skills?: string[];
      /** @example Kha Tran */
      name?: Record<string, never> | null;
      /** @example Ho Chi Minh City */
      location?: Record<string, never> | null;
      /** @example 1995 */
      bornYear?: Record<string, never> | null;
      /** @example khatran */
      github?: Record<string, never> | null;
      /** @example https://kha.dev */
      website?: Record<string, never> | null;
      /**
       * Format: date-time
       * @example 2026-05-17T16:59:32.000Z
       */
      createdAt: string;
    };
    LoginDto: {
      /** @example kha */
      username: string;
      /** @example strong-password-123 */
      password: string;
    };
    ChangePasswordDto: {
      /** @example current-pw */
      currentPassword: string;
      /** @example new-pw */
      newPassword: string;
    };
    ActivityActorDto: {
      id: string;
      username: string;
      avatarUrl: string | null;
    };
    ActivityTargetDto: {
      /** @enum {string} */
      type: 'POST' | 'COMMENT';
      id: string;
      /** @description Truncate 80 chars, null nếu target deleted */
      snippet: string | null;
    };
    ActivityItemDto: {
      id: string;
      /** @enum {string} */
      type: 'POST_CREATED' | 'COMMENT_CREATED' | 'LIKE_CREATED' | 'SAVE_CREATED';
      /** @enum {string} */
      direction: 'OUTGOING' | 'INCOMING';
      actor: components['schemas']['ActivityActorDto'];
      target: components['schemas']['ActivityTargetDto'];
      /** Format: date-time */
      createdAt: string;
    };
    PaginatedActivityDto: {
      items: components['schemas']['ActivityItemDto'][];
      total: number;
      page: number;
      limit: number;
    };
    MarkReadDto: {
      /** @example true */
      read: boolean;
    };
    BulkMarkReadDto: {
      ids: string[];
    };
    BulkDeleteDto: {
      ids: string[];
    };
    UserResponseDto: {
      /** @example cmpa14i8t000010ldmv5j5att */
      id: string;
      /** @example kha */
      username: string;
      /** @example kha@example.com */
      email: Record<string, never> | null;
      /**
       * @example USER
       * @enum {string}
       */
      role: 'ADMIN' | 'USER' | 'BANNED';
      /** @example https://...cloudinary.../avatar.jpg */
      avatarUrl: Record<string, never> | null;
      /**
       * @description FR-11.7 — Cloudinary publicId (chỉ admin/self thấy)
       * @example avatars/u-alice-1234567890
       */
      avatarPublicId?: Record<string, never> | null;
      /** @example Full-stack Developer */
      title?: Record<string, never> | null;
      /** @example Bio markdown... */
      bio?: Record<string, never> | null;
      /**
       * @description Skills array `[{ name, color }]`
       * @example [
       *       {
       *         "name": "TypeScript",
       *         "color": "#7DCFFF"
       *       }
       *     ]
       */
      skills?: string[];
      /** @example Kha Tran */
      name?: Record<string, never> | null;
      /** @example Ho Chi Minh City */
      location?: Record<string, never> | null;
      /** @example 1995 */
      bornYear?: Record<string, never> | null;
      /** @example khatran */
      github?: Record<string, never> | null;
      /** @example https://kha.dev */
      website?: Record<string, never> | null;
      /**
       * Format: date-time
       * @example 2026-05-17T16:59:32.000Z
       */
      createdAt: string;
    };
    PaginatedUsersDto: {
      items: components['schemas']['UserResponseDto'][];
      /** @example 42 */
      total: number;
      /** @example 1 */
      page: number;
      /** @example 20 */
      limit: number;
    };
    SetAvatarDto: {
      /**
       * @description Cloudinary secure_url returned từ direct upload
       * @example https://res.cloudinary.com/demo/image/upload/v1234567890/avatars/u-alice-1234.jpg
       */
      url: string;
      /**
       * @description Cloudinary publicId (folder avatars/ + userId prefix). Server validate prefix.
       * @example avatars/u-alice-1234567890
       */
      publicId: string;
    };
    AvatarResponseDto: {
      /** @example https://res.cloudinary.com/.../avatar.jpg */
      avatarUrl: Record<string, never> | null;
      /** @example avatars/u-alice-1234567890 */
      avatarPublicId: Record<string, never> | null;
    };
    SkillItemDto: {
      /** @example TypeScript */
      name: string;
      /** @example #7DCFFF */
      color: string;
    };
    UpdateUserDto: {
      /** @example kha */
      username?: string;
      /** @example kha@example.com */
      email?: string;
      /** @example https://res.cloudinary.com/.../avatar.jpg */
      avatarUrl?: string;
      /** @example Full-stack Developer */
      title?: string;
      /** @example Bio markdown... */
      bio?: string;
      /** @description Skills array — max 20 items */
      skills?: components['schemas']['SkillItemDto'][];
      /** @example Kha Tran */
      name?: string;
      /** @example Ho Chi Minh City */
      location?: string;
      /** @example 1995 */
      bornYear?: number;
      /** @example khatran */
      github?: string;
      /** @example https://kha.dev */
      website?: string;
    };
    SignUploadDto: {
      /**
       * @description Cloudinary folder (default: myblog)
       * @example myblog/posts
       */
      folder?: string;
      /**
       * @description Optional public_id override
       * @example post-abc-image-1
       */
      publicId?: string;
      /**
       * @description image cho PNG/JPG/WebP, raw cho PDF/DOC/...
       * @example image
       * @enum {string}
       */
      resourceType: 'image' | 'raw';
    };
    SignedUploadParamsDto: {
      /**
       * @example cloudinary
       * @enum {string}
       */
      provider: 'cloudinary' | 'local';
      /** @example abc123signaturehash */
      signature: string;
      /** @example 1715952000 */
      timestamp: number;
      /** @example 123456789012345 */
      apiKey: string;
      /** @example my-cloud */
      cloudName: string;
      /** @example myblog/posts */
      folder: string;
      /**
       * @example image
       * @enum {string}
       */
      resourceType: 'image' | 'raw';
      /** @example post-abc-image-1 */
      publicId: Record<string, never> | null;
      /**
       * @description Local driver: endpoint upload multipart
       * @example /files/upload
       */
      uploadUrl?: string;
    };
    UploadFileDto: {
      /** @example myblog/posts */
      folder: string;
      /**
       * @example image
       * @enum {string}
       */
      resourceType: 'image' | 'raw';
      /** @example u-abc-1717000000 */
      publicId?: string;
    };
    PopularTagDto: {
      /** @example cmpa1tag00010ldmv5j5att */
      id: string;
      /** @example dev */
      name: string;
      /** @example #00FFE5 */
      color: Record<string, never> | null;
      /** @example Lập trình, debugging */
      description?: Record<string, never> | null;
      /** @example 5 */
      postCount: number;
      /**
       * @description Last 7 days post-with-tag count
       * @example [
       *       0,
       *       1,
       *       2,
       *       1,
       *       0,
       *       3,
       *       1
       *     ]
       */
      sparkline7d: string[];
      /** @example 2026-05-19T00:00:00.000Z */
      createdAt: string;
    };
    PopularTagsResponseDto: {
      items: components['schemas']['PopularTagDto'][];
    };
    CreateTagDto: {
      /**
       * @description Tag name (auto-normalize lowercase + strip #)
       * @example dev
       */
      name: string;
      /**
       * @description Hex color, auto-assign từ palette nếu thiếu
       * @example #00FFE5
       */
      color?: string;
      /** @example Lập trình, debugging */
      description?: string;
    };
    TagResponseDto: {
      /** @example cmpa1tag00010ldmv5j5att */
      id: string;
      /** @example dev */
      name: string;
      /** @example #00FFE5 */
      color: Record<string, never> | null;
      /** @example Lập trình, debugging */
      description?: Record<string, never> | null;
    };
    UpdateTagDto: {
      /**
       * @description Tag name (auto-normalize lowercase + strip #)
       * @example dev
       */
      name?: string;
      /**
       * @description Hex color, auto-assign từ palette nếu thiếu
       * @example #00FFE5
       */
      color?: string;
      /** @example Lập trình, debugging */
      description?: string;
    };
    PostAuthorDto: {
      /** @example cmpa14i8t000010ldmv5j5att */
      id: string;
      /** @example kha */
      username: string;
      /**
       * @description Display name (FR-11.8)
       * @example Kha Tran
       */
      name: Record<string, never> | null;
      /**
       * @example ADMIN
       * @enum {string}
       */
      role: 'ADMIN' | 'USER' | 'BANNED';
      /** @example https://...avatar.jpg */
      avatarUrl: Record<string, never> | null;
    };
    PostTagDto: {
      /** @example cmpa1tg00000010ldmv5j5att */
      id: string;
      /** @example dev */
      name: string;
      /** @example #7AF7FF */
      color: Record<string, never> | null;
    };
    PostImageDto: {
      id: string;
      url: string;
      publicId: string;
      /** @example 1920 */
      width: number;
      /** @example 1080 */
      height: number;
      /** @example 0 */
      order: number;
    };
    PostFileDto: {
      id: string;
      name: string;
      /** @enum {string} */
      type: 'PDF' | 'DOC' | 'DOCX' | 'XLS' | 'XLSX' | 'TXT' | 'CSV';
      /** @example 102400 */
      size: number;
      url: string;
      publicId: string;
    };
    PostCountsDto: {
      /** @example 5 */
      reactions: number;
      /** @example 3 */
      comments: number;
    };
    PostResponseDto: {
      /** @example cmpa1post00010ldmv5j5att */
      id: string;
      content: string;
      /** @enum {string} */
      mood: 'HAPPY' | 'EXCITED' | 'THOUGHTFUL' | 'CALM' | 'SAD' | 'GRATEFUL' | 'ANGRY';
      /** @example 0 */
      viewCount: number;
      author: components['schemas']['PostAuthorDto'];
      tags: components['schemas']['PostTagDto'][];
      images: components['schemas']['PostImageDto'][];
      files: components['schemas']['PostFileDto'][];
      counts: components['schemas']['PostCountsDto'];
      /**
       * @description Top 3 reaction types by count (desc). Empty if no reactions.
       * @example [
       *       "LIKE",
       *       "LOVE",
       *       "HAHA"
       *     ]
       */
      topReactions: ('LIKE' | 'LOVE' | 'HAHA' | 'WOW' | 'SAD' | 'ANGRY')[];
      /**
       * @description Viewer reaction on this post; null if no viewer or not reacted.
       * @example LIKE
       * @enum {string|null}
       */
      myReaction: 'LIKE' | 'LOVE' | 'HAHA' | 'WOW' | 'SAD' | 'ANGRY' | null;
      /**
       * Format: date-time
       * @example 2026-05-17T16:59:32.000Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @example 2026-05-17T16:59:32.000Z
       */
      updatedAt: string;
    };
    PaginatedPostsDto: {
      items: components['schemas']['PostResponseDto'][];
      /** @example 42 */
      total: number;
      /** @example 1 */
      page: number;
      /** @example 10 */
      limit: number;
    };
    ImageInputDto: {
      /** @example https://res.cloudinary.com/.../img.jpg */
      url: string;
      /** @example myblog/posts/abc123 */
      publicId: string;
      /** @example 1920 */
      width: number;
      /** @example 1080 */
      height: number;
      /**
       * @default 0
       * @example 0
       */
      order: number;
    };
    FileInputDto: {
      /** @example report.pdf */
      name: string;
      /**
       * @example PDF
       * @enum {string}
       */
      type: 'PDF' | 'DOC' | 'DOCX' | 'XLS' | 'XLSX' | 'TXT' | 'CSV';
      /** @example 102400 */
      size: number;
      /** @example https://res.cloudinary.com/.../report.pdf */
      url: string;
      /** @example myblog/files/report-xyz */
      publicId: string;
    };
    CreatePostDto: {
      /** @example Hôm nay code rất vui... */
      content: string;
      /**
       * @example HAPPY
       * @enum {string}
       */
      mood: 'HAPPY' | 'EXCITED' | 'THOUGHTFUL' | 'CALM' | 'SAD' | 'GRATEFUL' | 'ANGRY';
      /**
       * @description Tag names (with or without # prefix). Auto-create if not exists.
       * @example [
       *       "#dev",
       *       "#life"
       *     ]
       */
      tags?: string[];
      images?: components['schemas']['ImageInputDto'][];
      files?: components['schemas']['FileInputDto'][];
    };
    UpdatePostDto: {
      /** @example Hôm nay code rất vui... */
      content?: string;
      /**
       * @example HAPPY
       * @enum {string}
       */
      mood?: 'HAPPY' | 'EXCITED' | 'THOUGHTFUL' | 'CALM' | 'SAD' | 'GRATEFUL' | 'ANGRY';
      /**
       * @description Tag names (with or without # prefix). Auto-create if not exists.
       * @example [
       *       "#dev",
       *       "#life"
       *     ]
       */
      tags?: string[];
      images?: components['schemas']['ImageInputDto'][];
      files?: components['schemas']['FileInputDto'][];
    };
    TrackViewResponseDto: {
      /**
       * @description Tổng viewCount sau khi (có thể) increment
       * @example 42
       */
      viewCount: number;
      /**
       * @description true nếu view được tính (record mới); false nếu bị dedup trong 30 phút
       * @example true
       */
      counted: boolean;
    };
    UpsertReactionDto: {
      /**
       * @description Kiểu reaction
       * @example LOVE
       * @enum {string}
       */
      type: 'LIKE' | 'LOVE' | 'HAHA' | 'WOW' | 'SAD' | 'ANGRY';
    };
    InteractionLogActorDto: {
      /** @example usr_abc */
      id: string;
      /** @example alice */
      username: string;
    };
    InteractionLogResponseDto: {
      /** @example log_abc */
      id: string;
      /** @enum {string} */
      action: 'COMMENT' | 'REPLY' | 'COMMENT_LIKE' | 'POST_REACTION';
      /** @enum {string} */
      targetType: 'POST' | 'COMMENT';
      /** @example post_abc */
      targetId: string;
      /** @example post_abc */
      postId: Record<string, never> | null;
      /** @description null = anonymous */
      actor: components['schemas']['InteractionLogActorDto'] | null;
      /**
       * @description null = anonymous
       * @enum {string|null}
       */
      actorRole: 'ADMIN' | 'USER' | 'BANNED' | null;
      /** @example 0x7F4A2C */
      anonymousId: Record<string, never> | null;
      /** @example 203.0.113.7 */
      ip: Record<string, never> | null;
      /** @example Mozilla/5.0 ... */
      userAgent: Record<string, never> | null;
      /** @example Chrome 120.0.0.0 */
      browser: Record<string, never> | null;
      /** @example macOS 10.15.7 */
      os: Record<string, never> | null;
      /** @example desktop */
      device: Record<string, never> | null;
      /** @example vi-VN */
      acceptLang: Record<string, never> | null;
      /** @example http://localhost:5173/ */
      referer: Record<string, never> | null;
      /**
       * @description ISO country code từ IP (geoip)
       * @example VN
       */
      geoCountry: Record<string, never> | null;
      /** @example Ho Chi Minh City */
      geoCity: Record<string, never> | null;
      /** @example a1b2c3d4e5f6a7b8 */
      fingerprint: Record<string, never> | null;
      metadata: {
        [key: string]: unknown;
      } | null;
      /**
       * Format: date-time
       * @example 2026-05-31T10:00:00.000Z
       */
      createdAt: string;
    };
    InteractionLogsListResponseDto: {
      items: components['schemas']['InteractionLogResponseDto'][];
      /** @example 128 */
      total: number;
      /** @example 1 */
      page: number;
      /** @example 20 */
      limit: number;
    };
    CommentAuthorDto: {
      /** @example cmpa-user-1 */
      id: string;
      /** @example kha */
      username: string;
      /**
       * @description Display name (FR-11.8)
       * @example Kha Tran
       */
      name: Record<string, never> | null;
      /**
       * @example USER
       * @enum {string}
       */
      role: 'ADMIN' | 'USER' | 'BANNED';
      /** @example https://.../avatar.jpg */
      avatarUrl: Record<string, never> | null;
    };
    CommentResponseDto: {
      /** @example cmpa-comment-1 */
      id: string;
      /** @example cmpa-post-1 */
      postId: string;
      /** @example Bài hay quá! */
      content: string;
      /**
       * @example APPROVED
       * @enum {string}
       */
      status: 'PENDING' | 'APPROVED' | 'REJECTED';
      /** @description null nếu anonymous */
      author: components['schemas']['CommentAuthorDto'] | null;
      /** @example Khách qua đường */
      anonymousName: Record<string, never> | null;
      /** @example 3 */
      likesCount: number;
      /** @example cmpa-comment-parent */
      parentId: Record<string, never> | null;
      /**
       * @description Denormalized parent author info (reply only)
       * @example {
       *       "username": "kha",
       *       "isAnon": false
       *     }
       */
      replyTo: Record<string, never> | null;
      /**
       * Format: date-time
       * @example 2026-05-18T10:00:00.000Z
       */
      createdAt: string;
    };
    CommentsListResponseDto: {
      items: components['schemas']['CommentResponseDto'][];
    };
    CreateCommentDto: {
      /** @example Bài viết rất hay! */
      content: string;
      /**
       * @description Tên hiển thị cho anonymous (ignored nếu auth)
       * @example Khách qua đường
       */
      anonymousName?: string;
      /**
       * @description Parent comment id để reply (FR-03.6, depth 1 only)
       * @example cmpa-comment-1
       */
      parentId?: string;
    };
    CommentRepliesResponseDto: {
      items: components['schemas']['CommentResponseDto'][];
      /** @example 42 */
      total: number;
      /** @example 1 */
      page: number;
      /** @example 20 */
      limit: number;
    };
    UpdateCommentStatusDto: {
      /**
       * @description PENDING không cho phép via PATCH — chỉ APPROVED | REJECTED
       * @example APPROVED
       * @enum {string}
       */
      status: 'APPROVED' | 'REJECTED';
    };
    ToggleSaveResponseDto: {
      /**
       * @description Trạng thái bookmark sau toggle
       * @example true
       */
      saved: boolean;
    };
    SavedPostDto: {
      /** @example cmpa1post00010ldmv5j5att */
      id: string;
      content: string;
      /** @enum {string} */
      mood: 'HAPPY' | 'EXCITED' | 'THOUGHTFUL' | 'CALM' | 'SAD' | 'GRATEFUL' | 'ANGRY';
      /** @example 0 */
      viewCount: number;
      author: components['schemas']['PostAuthorDto'];
      tags: components['schemas']['PostTagDto'][];
      images: components['schemas']['PostImageDto'][];
      files: components['schemas']['PostFileDto'][];
      counts: components['schemas']['PostCountsDto'];
      /**
       * @description Top 3 reaction types by count (desc). Empty if no reactions.
       * @example [
       *       "LIKE",
       *       "LOVE",
       *       "HAHA"
       *     ]
       */
      topReactions: ('LIKE' | 'LOVE' | 'HAHA' | 'WOW' | 'SAD' | 'ANGRY')[];
      /**
       * @description Viewer reaction on this post; null if no viewer or not reacted.
       * @example LIKE
       * @enum {string|null}
       */
      myReaction: 'LIKE' | 'LOVE' | 'HAHA' | 'WOW' | 'SAD' | 'ANGRY' | null;
      /**
       * Format: date-time
       * @example 2026-05-17T16:59:32.000Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @example 2026-05-17T16:59:32.000Z
       */
      updatedAt: string;
      /**
       * Format: date-time
       * @description Thời điểm save bài
       * @example 2026-05-18T10:00:00.000Z
       */
      savedAt: string;
    };
    PaginatedSavedDto: {
      items: components['schemas']['SavedPostDto'][];
      /** @example 12 */
      total: number;
      /** @example 1 */
      page: number;
      /** @example 10 */
      limit: number;
    };
    MetricBucketDto: {
      /** @example 42 */
      total: number;
      /**
       * @example [
       *       0,
       *       1,
       *       0,
       *       3,
       *       2,
       *       1,
       *       4,
       *       0,
       *       2,
       *       1,
       *       3,
       *       5
       *     ]
       */
      sparkline: number[];
      /**
       * @description count today - count yesterday
       * @example 3
       */
      deltaToday: number;
    };
    StatsResponseDto: {
      posts: components['schemas']['MetricBucketDto'];
      reactions: components['schemas']['MetricBucketDto'];
      comments: components['schemas']['MetricBucketDto'];
      views: components['schemas']['MetricBucketDto'];
    };
    MoodCountDto: {
      /**
       * @example HAPPY
       * @enum {string}
       */
      mood: 'HAPPY' | 'EXCITED' | 'THOUGHTFUL' | 'CALM' | 'SAD' | 'GRATEFUL' | 'ANGRY';
      /** @example 5 */
      count: number;
    };
    MoodsResponseDto: {
      items: components['schemas']['MoodCountDto'][];
    };
    HeatmapDayDto: {
      /** @example 2026-05-18 */
      date: string;
      /** @example 3 */
      count: number;
    };
    HeatmapResponseDto: {
      days: components['schemas']['HeatmapDayDto'][];
    };
    UpdateAdminPostDto: {
      /** @example Updated content */
      content?: string;
      /** @enum {string} */
      mood?: 'HAPPY' | 'EXCITED' | 'THOUGHTFUL' | 'CALM' | 'SAD' | 'GRATEFUL' | 'ANGRY';
      /** @enum {string} */
      status?: 'PUBLISHED' | 'DRAFT' | 'ARCHIVED';
      /**
       * @example [
       *       "dev",
       *       "tech"
       *     ]
       */
      tags?: string[];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  AppController_ping: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AppController_health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_register: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthUserDto'];
        };
      };
    };
  };
  AuthController_login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthUserDto'];
        };
      };
    };
  };
  AuthController_refresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthUserDto'];
        };
      };
    };
  };
  AuthController_logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthUserDto'];
        };
      };
    };
  };
  AuthController_changePassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ChangePasswordDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ActivityController_list: {
    parameters: {
      query?: {
        page?: number;
        limit?: number;
      };
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PaginatedActivityDto'];
        };
      };
    };
  };
  NotificationsController_list: {
    parameters: {
      query?: {
        filter?: 'all' | 'unread';
        page?: number;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  NotificationsController_unreadCount: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  NotificationsController_markAllRead: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  NotificationsController_markRead: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['MarkReadDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  NotificationsController_bulkMarkRead: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['BulkMarkReadDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  NotificationsController_deleteAll: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  NotificationsController_deleteBulk: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['BulkDeleteDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  NotificationsController_deleteOne: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_list: {
    parameters: {
      query?: {
        role?: 'ADMIN' | 'USER' | 'BANNED';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PaginatedUsersDto'];
        };
      };
    };
  };
  UsersController_signAvatar: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_removeAvatar: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AvatarResponseDto'];
        };
      };
    };
  };
  UsersController_setAvatar: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SetAvatarDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AvatarResponseDto'];
        };
      };
    };
  };
  UsersController_getByUsername: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        username: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_getStats: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponseDto'];
        };
      };
    };
  };
  UsersController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateUserDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponseDto'];
        };
      };
    };
  };
  UsersController_ban: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponseDto'];
        };
      };
    };
  };
  UsersController_unban: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponseDto'];
        };
      };
    };
  };
  FilesController_signUpload: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SignUploadDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SignedUploadParamsDto'];
        };
      };
    };
  };
  FilesController_upload: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['UploadFileDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FilesController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TagsController_list: {
    parameters: {
      query?: {
        sort?: 'name' | 'posts' | 'recent';
        /** @description Substring filter on tag name */
        q?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PopularTagsResponseDto'];
        };
      };
    };
  };
  TagsController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateTagDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TagResponseDto'];
        };
      };
    };
  };
  TagsController_remove: {
    parameters: {
      query: {
        force: string;
      };
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TagsController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateTagDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TagResponseDto'];
        };
      };
    };
  };
  PostsController_list: {
    parameters: {
      query?: {
        mood?: 'HAPPY' | 'EXCITED' | 'THOUGHTFUL' | 'CALM' | 'SAD' | 'GRATEFUL' | 'ANGRY';
        /** @description Tag name (with or without # prefix) */
        tag?: string;
        sort?: 'latest' | 'oldest' | 'likes';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PaginatedPostsDto'];
        };
      };
    };
  };
  PostsController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreatePostDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PostResponseDto'];
        };
      };
    };
  };
  PostsController_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PostResponseDto'];
        };
      };
    };
  };
  PostsController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PostsController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdatePostDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PostResponseDto'];
        };
      };
    };
  };
  PostsController_trackView: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TrackViewResponseDto'];
        };
      };
    };
  };
  ReactionsController_listReactions: {
    parameters: {
      query?: {
        /** @description Filter by reaction type */
        type?: 'LIKE' | 'LOVE' | 'HAHA' | 'WOW' | 'SAD' | 'ANGRY';
        page?: number;
        limit?: number;
      };
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ReactionsController_upsertReaction: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpsertReactionDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ReactionsController_removeReaction: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ReactionsController_getReactionCounts: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ReactionsController_legacyLike: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Gone — endpoint replaced by /reactions */
      410: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ReactionsController_toggleCommentLike: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  InteractionLogsController_list: {
    parameters: {
      query?: {
        /** @description Filter theo loại hành động */
        action?: 'COMMENT' | 'REPLY' | 'COMMENT_LIKE' | 'POST_REACTION';
        /** @description anon = chưa login, user = USER */
        actorType?: 'anon' | 'user';
        /** @description Tìm trong ip / fingerprint / anonymousId / userAgent */
        q?: string;
        /** @description Từ ngày (ISO 8601) — lọc createdAt >= */
        from?: string;
        /** @description Đến ngày (ISO 8601) — lọc createdAt <= */
        to?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['InteractionLogsListResponseDto'];
        };
      };
    };
  };
  CommentsController_list: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CommentsListResponseDto'];
        };
      };
    };
  };
  CommentsController_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateCommentDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CommentResponseDto'];
        };
      };
    };
  };
  CommentsController_listReplies: {
    parameters: {
      query?: {
        page?: number;
        limit?: number;
      };
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CommentRepliesResponseDto'];
        };
      };
    };
  };
  CommentsController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CommentsController_updateStatus: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateCommentStatusDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CommentResponseDto'];
        };
      };
    };
  };
  SavedController_toggle: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ToggleSaveResponseDto'];
        };
      };
    };
  };
  SavedController_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PaginatedSavedDto'];
        };
      };
    };
  };
  SearchController_query: {
    parameters: {
      query?: {
        /** @description Search query (empty → stats only) */
        q?: string;
        type?: 'all' | 'posts' | 'files' | 'tags' | 'saved';
        mood?: 'HAPPY' | 'EXCITED' | 'THOUGHTFUL' | 'CALM' | 'SAD' | 'GRATEFUL' | 'ANGRY';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminController_testReset: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminController_stats: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StatsResponseDto'];
        };
      };
    };
  };
  AdminController_moods: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MoodsResponseDto'];
        };
      };
    };
  };
  AdminController_listComments: {
    parameters: {
      query?: {
        status?: 'PENDING' | 'APPROVED' | 'REJECTED';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminController_heatmap: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HeatmapResponseDto'];
        };
      };
    };
  };
  AdminController_listPosts: {
    parameters: {
      query?: {
        status?: 'PUBLISHED' | 'DRAFT' | 'ARCHIVED';
        mood?: 'HAPPY' | 'EXCITED' | 'THOUGHTFUL' | 'CALM' | 'SAD' | 'GRATEFUL' | 'ANGRY';
        sort?: 'latest' | 'oldest' | 'likes';
        /** @description Full-text search in content */
        q?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminController_deletePost: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminController_updatePost: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateAdminPostDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
